### ISSUE TITLE
request to add traits to identify

### ISSUE THREAD

**Issue by Matthew-simms** [freska-fi/segment_flutter_sdk#5]
would be great to have traits added to _segmentTracker.identify so we can add important user information such as name, email, gender etc.. for use in marketing platforms such as Mailchimp, customer.io etc.

**Comment by jonyas** [comment]
@Matthew-simms we are preparing a pull request that contains `traits` as optional parameter when identifying users.

Thanks for the suggestion!

**Comment by jonyas** [comment]
Feature was added to our latest release: https://pub.dev/packages/segment_flutter_sdk
